### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by qayyumfridi** [romainrg/codeigniter-ratchet-websocket#1]
WebSocket connection to 'ws://192.168.1.2:8282/' failed: Received a broken close frame containing a reserved status code.

If i use your javascript code it is working. If i use angularjs it show above error. I am using this library 
https://github.com/gdi2290/angular-websocket
here is my sample data 
onOpen connection open{"user_id":"526","recipient_id":1,"message":null}

connection Error Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
connection closed CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …}

Can you please guide me. 
Thank you

**Comment by romainrg** [comment]
Hi,

Websocket returncode 1006 means your authentication callback not passed successfully, can you show me your auth callback function ?

**Comment by qayyumfridi** [comment]
Thanks for your replay. I haven't changed any thing  in code you demo in github. this is what i am using

**Comment by qayyumfridi** [comment]
public function _auth($datas = null)
    {
        // Here you can verify everything you want to perform user login.
        // However, method must return integer (client ID) if auth succedeed and false if not.
        return (!empty($datas->user_id)) ? $datas->user_id : false;
    }

**Comment by qayyumfridi** [comment]
Hello romainrg

I am waiting for your response.

**Comment by romainrg** [comment]
Hello @qayyumfridi,

Can you also send me the datas given to websocket ?

**Comment by qayyumfridi** [comment]
This is what i am using
var client = {
            user_id:526,
            recipient_id: null,
            message: null
        };

**Comment by qayyumfridi** [comment]
I found something else when i turn off authentication it start showing connection is open correctly 
for this data 
var client = {
user_id:526,
recipient_id: null,
message: null
};
after you type message and provide recipient_id (527 which is also connected user my case) it never send message using your demo code and never show any debug notification cmd. 

I am waiting for your reply

**Comment by qayyumfridi** [comment]
I am using your code with some modifications. This is without authentication functionality
 
var client = {
        user_id:$scope.sessionobj.studentinfo.id,
        recipient_id: null,
        message: null
    };

    var conn = new WebSocket('ws://192.168.1.2:8282');
 
   **This section is working**

    conn.onopen = function(e) {
        conn.send(JSON.stringify(client));
    };
   
   **This section is not working**
   **No event call is occurring**

    conn.onmessage = function(e) {
        var data = JSON.parse(e.data);
    };

  **this is on button click function**
     $scope.sendtext = function(m)
    {
        try{
            client.message = m.text.trim();
            client.recipient_id = m.id;
            conn.send(JSON.stringify(client));
        }
        catch(e){
             console.log(e);
        }
    }

**Comment by qayyumfridi** [comment]
Thanks for your no response.
